/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.az.fatalstrike;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;

import org.junit.Test;

import de.gurkenlabs.litiengine.Game;
import de.gurkenlabs.litiengine.graphics.TextRenderer;
import de.gurkenlabs.litiengine.gui.screens.GameScreen;

public class AppTest
{
	@Test public void testTextRendering()
	{
		long time = System.currentTimeMillis();
		Game.init();
		Game.start();
		Game.screens().display(new TestScreen());
		
		while (System.currentTimeMillis() <  time + 10000);
	}
	
	class TestScreen extends GameScreen
	{
		public TestScreen() { super("test"); }
		private double angle = 0;
		private int coord = 0;
		
		@Override
		public void render(Graphics2D graphics)
		{
			super.render(graphics);
			
			graphics.setFont(Font.getFont("Consolas 10"));
			graphics.setColor(Color.ORANGE);
			TextRenderer.renderRotated(graphics, "TEST", coord++, coord, angle += 3.6);
		}
	}
}
